name: Lambda 

on:
  push:
    paths:
    - 'app/lalalambda/**'
    branches: 
    - main
  pull_request:
    paths:
    - 'app/lalalambda/**'
    branches:
    - main
  workflow_dispatch:

jobs:

  send-to-lambda:

    name: Lambda Pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
