AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API for making an online compiler of lalalang

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowOrigin: "'*'"

Resources:

  CompileLaLaLang:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: compile/
      Handler: lambda.handler
      Runtime: python3.9
      Events:
        Compile:
          Type: Api 
          Properties:
            Path: /
            Method: post

Outputs:
  LaLaLangApi:
    Description: "API Gateway endpoint for compiling lalalang"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CompileLaLaLang:
    Description: "Compile Function Arn"
    Value: !GetAtt CompileLaLaLang.Arn
